/gazebo_ros_control/pid_gains:
    ur5_arm_shoulder_pan_joint:
      p: 100.0
      i: 0.01 
      d: 10.0
    ur5_arm_shoulder_lift_joint:
      p: 100.0
      i: 0.01 
      d: 10.0  
    ur5_arm_elbow_joint:
      p: 100.0
      i: 0.01 
      d: 10.0
    ur5_arm_wrist_1_joint:
      p: 100.0
      i: 0.01 
      d: 10.0
    ur5_arm_wrist_2_joint:
      p: 100.0
      i: 0.01 
      d: 10.0
    ur5_arm_wrist_3_joint:
      p: 100.0
      i: 0.01 
      d: 10.0
    front_left_wheel:
      p: 100.0
      i: 0.01 
      d: 10.0
    front_right_wheel:
      p: 100.0
      i: 0.01 
      d: 10.0
    rear_left_wheel:
      p: 100.0
      i: 0.01 
      d: 10.0
    rear_right_wheel:
      p: 100.0
      i: 0.01 
      d: 10.0
   
